### ISSUE TITLE
Test cases and examples are uploaded to NPM

### ISSUE THREAD

**Issue by tbodt** [browserify/resolve#207] opened 2020-01-22 05:09 UTC
Should be pretty easy to fix by whitelisting the necessary files in package.json:
```json
{
  "files": [
    "lib",
    "index.js"
  ]
}
```

**Comment by ljharb** [comment] 2020-01-22 05:22
There’s nothing to fix; they’re included by design. `npm install foo && npm explore foo && npm install && npm test` should always work.

Separately, the files field is very dangerous and should be avoided in favor of npmignore.

Duplicate of #171. Duplicate of #180. See not just #82, but https://github.com/browserify/resolve/pull/149#pullrequestreview-96750692, https://github.com/browserify/resolve/pull/132#pullrequestreview-52259150, https://github.com/browserify/resolve/pull/128#pullrequestreview-47539920, https://github.com/browserify/resolve/pull/59#issuecomment-63429177, 
https://github.com/browserify/resolve/issues/164#issuecomment-395570164,  https://github.com/browserify/resolve/issues/171#issuecomment-434526430

**Closed by ljharb** 2020-01-22 05:22 UTC

**Comment by tbodt** [comment] 2020-01-22 05:54
TIL about npm explore.
