### ISSUE TITLE
Used  monorepo-symlink-test is malicious

### ISSUE THREAD

**Issue by ThomazPom** [browserify/resolve#314] opened 2023-09-08 13:53 UTC
Hello
[This file](https://github.com/browserify/resolve/blob/main/test/resolver/multirepo/package.json) is using monorepo-symlink-test which is a malicious package [described here](
https://snyk.io/advisor/npm-package/monorepo-symlink-test)

Could you please remove this file which seems useless ?

Thank you

**Comment by ljharb** [comment] 2023-09-08 15:21
> Because it's a private package that just coincidentally has the same name as the malicious one, it is a false positive - so whatever tool is flagging this repo is broken, and you should strongly reconsider using a tool that is this naive about npm package names.

Duplicate of https://github.com/browserify/resolve/issues/303. Duplicate of https://github.com/browserify/resolve/issues/291. Duplicate of https://github.com/browserify/resolve/issues/288. Duplicate of https://github.com/browserify/resolve/issues/304. Duplicate of https://github.com/browserify/resolve/issues/305. Duplicate of https://github.com/browserify/resolve/issues/306. Duplicate of https://github.com/browserify/resolve/issues/309. Duplicate of #310. Duplicate of #311. Duplicate of #312.

It’s not useless; tests must be shipped with packages so that `npm explore foo && npm install && npm test` always works.

**Closed as not planned by ljharb** 2023-09-08 15:21 UTC
