### ISSUE TITLE
`NODE_PATH` environment variable is ignored

### ISSUE THREAD

**Issue by RichardBradley** [browserify/resolve#136] opened 2017-09-19 16:13 UTC
The "node require.resolve() algorithm" should also search in the directories listed in the `$NODE_PATH` environment variable, if it is set. See docs here: https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

Currently, the `resolve` library does not implement this step, but I think it should.

I need this because I am running with my *local* `node_modules` directory outside of my project dir, as per [this workaround](https://github.com/npm/npm/issues/775#issuecomment-50301534), because my project dir does not support symlinks (a shared folder).

Because `resolve` ignores the  `$NODE_PATH` environment variable, `grunt` refuses to run.

**Comment by ljharb** [comment] 2017-09-19 20:20
This is a duplicate of #39; see https://github.com/browserify/resolve/issues/39#issuecomment-306223854.

I wouldn't suggest using `NODE_PATH` for anything; any workaround using it is worse than other alternatives.

**Closed by ljharb** 2017-09-19 20:20 UTC

**Comment by RichardBradley** [comment] 2017-09-19 22:21
Thanks, sorry for not spotting that.

> I wouldn't suggest using NODE_PATH for anything; any workaround using it is worse than other alternatives.

Do you know what my other options are for an `npm install` on a file system that doesn't support symlinks, then?

The only practical workaround I have been able to find so far is the `NODE_PATH` based workaround I linked to above.

**Comment by ljharb** [comment] 2017-09-19 22:52
Using `file://` will copy-on-install; if your filesystem doesn't support symlinks tho, nor hard mounts, I'm not sure how to handle that.

What filesystem/OS are you using that doesn't support symlinks?

**Comment by RichardBradley** [comment] 2017-09-19 23:46
> What filesystem/OS are you using that doesn't support symlinks?

VMWare HGFS in a guest linux VM, backed by an NTFS dir on the Windows host machine.

> Using file:// will copy-on-install;

I don't understand this, sorry. Where do I use "file://"? What do you mean by copy-on-install in this context?

**Comment by ljharb** [comment] 2017-09-20 01:05
Ah, I'm not familiar with HGFS; although NTFS certainly supports symlinks.

In `package.json`: `"packageName": "file://path/to/dir"` will *copy* those files on `npm install` to your local `node_modules`.

**Comment by RichardBradley** [comment] 2017-09-20 10:48
I have found a workaround which I think I can live with for now:
 1. Copy the `project.json` file to a temp folder on a different FS
 2. Run `npm install` there
 3. Copy the resulting `node_modules` directory back into the project dir, using `cp -r --dereference` to expand symlinks into copies.

> Ah, I'm not familiar with HGFS; although NTFS certainly supports symlinks.

It does, but they're not commonly used. I believe that the Windows installers for `npm` avoid creating symlinks for that reason. The problem for me is that I am running on Linux and the `npm` installers all assume that they are free to create symlinks.

Regarding the "file://" urls and "copy-on-install", I don't see how that's relevant to my goal of running `npm install` on a node project on linux when my filesystem doesn't support symlinks, but I suspect we're talking past each other on that one.

Thanks for your help!
