### ISSUE TITLE
Error "ENOENT: no such file or directory, open '../../is-core-module/core.json"

### ISSUE THREAD

**Issue by SuperOleg39** [browserify/resolve#297] opened 2023-04-17 13:52 UTC
Hello @ljharb!

Have this error in last `resolve` package version - `ENOENT: no such file or directory, open '../../is-core-module/core.json`

This change is breaking change for bundlers - https://github.com/browserify/resolve/commit/122bb64be2f4fcf927fd264d4b2c9ea622611c58, because bundler can't process this require anymore.

Our case - we using `webpack` for server code (SSR application)

May I ask you to revert this change?

**Comment by ljharb** [comment] 2023-04-17 14:37
The core.js import is deprecated; you should be using is-core-module directly. That said, I’ll see what i can do.

**Comment by SuperOleg39** [comment] 2023-04-17 15:29
```
var async = require('./lib/async');
async.core = require('./lib/core');
async.isCore = require('./lib/is-core');
async.sync = require('./lib/sync');

module.exports = async;
```

It is code from library current version entry point, webpack trying to process all imports here

**Comment by ljharb** [comment] 2023-04-17 16:20
tbh tho I'm surprised webpack wouldn't be able to see the fs.readFileSync call and inline the file's contents.

**Comment by oksankaa** [comment] 2023-04-17 18:11
We have the same issue and also use webpack.

**Comment by SuperOleg39** [comment] 2023-04-17 18:43
> tbh tho I'm surprised webpack wouldn't be able to see the fs.readFileSync call and inline the file's contents.

It is quite impossible)
Popular bundlers have support for import/require with dynamic paths, but it is very limited by bunch of reasons

**Comment by oksankaa** [comment] 2023-04-17 18:44
> @oksankaa you're also bundling on the server?

yes

**Comment by foolzhang** [comment] 2023-04-20 11:22
![企业微信截图_16819760615145](https://user-images.githubusercontent.com/5095651/233351372-cd915c7e-12cd-4194-a2a1-7c97b0a68c4a.png)

**Comment by JKapitein** [comment] 2023-04-27 12:09
For us it's generating the following in webpack:

`var data = JSON.parse(String(fs.readFileSync(path.join(path.dirname(/*require.resolve*/(91928)), 'core.json'))));`

This obviously breaks because dirname won't take a number argument.

**Comment by trentm** [comment] 2023-05-23 18:51
@ljharb Do you intend to keep resolve@1.x using `var data = require('./core.json');`?  (I'm inferring that was the intent, at least for the short term, by the "latest" dist-tag having moved to '1.22.2'.

I'm currently maintaining `require-in-the-middle` and will try to get it to work with bundlers. I haven't looked at the resolve@2.x pre-releases yet.

**Comment by ljharb** [comment] 2023-05-23 18:55
@trentm tbh I'm not sure yet. Keeping it that way means the data will be out of date between releases of resolve, and avoiding that (deferring it to `is-core-module`) was the goal.

**Comment by trentm** [comment] 2023-05-23 23:33
One option would be to have a release of `is-core-module` with an export for "core.json":

```diff
diff --git a/package.json b/package.json
index 62bb065..078f73d 100644
--- a/package.json
+++ b/package.json
@@ -6,6 +6,7 @@
        "sideEffects": false,
        "exports": {
                ".": "./index.js",
+               "./core.json": "./core.json",
                "./package.json": "./package.json"
        },
        "scripts": {
```

then in `resolve@1.x` one could do:

```js
var data = require('is-core-module/core.json');
```

---

However, I could understand if you don't want to do that (it adds API surface area to `is-core-module`) and just wanted to move forward with `resolve@2.x`. 

If/when you release a version of `resolve@2.x`, and as long as it still supports node >=8.6.0, I can update `require-in-the-middle` to use `resolve` and `is-core-module` as needed.

Thanks for maintaining these modules.

**Comment by ljharb** [comment] 2023-05-24 05:04
You're exactly right, and I want very much not to add to the API surface area of `is-core-module`.

`resolve` already has v2 prereleases, and I'd encourage you to use it! (and will support down to node 0.4 for the foreseeable future)

That said, I still need to figure out a fix for this in v1, and the current options, as you've accurately described, are:
1. do nothing, allow resolve v1 to be out of date between an `is-core-module` publish until the next v1 publish
1. add `core.json` to `is-core-module`
1. build some kind of complex multiple-file solution with the "browser" field, so that node uses readFileSync and browsers use `require`, meaning that a bundler that uses `require` but still respects "exports" would have the problem in the first bullet point

and none of those options are pleasant.

**Comment by schmalzs** [comment] 2023-08-01 20:43
Hi all -- appreciate your thought on this issue. I see there hasn't been a lot of activity and wanted to see if there feels like a viable path forward for v1.

Although v1.22.2 is currently marked as `latest`, I'm hitting issues with `v1.22.3` continuing to get pulled into my app. I can't quite tell why -- it may be some kind of transitive dependency that is still referencing `^v1.22.3`. For what it's worth, I'm using Yarn as the package manager.

I'm curious if there's any appetite to publish out a `v1.22.4` which rolls back the change introduced in `v1.22.3`.

For additional context, I'm hitting the problem from pulling in `@opentelemetry/instrumentation` which has a transitive dependency on `resolve` by way of `require-in-the-middle`.

**Comment by ljharb** [comment] 2023-08-01 20:47
Yes, that seems like a reasonable thing to do given the length of time it’s taken to figure this out. I’m traveling right now, but will do that at the first opportunity.

**Comment by EAGzzyCSL** [comment] 2023-08-02 13:18
> Hi all -- appreciate your thought on this issue. I see there hasn't been a lot of activity and wanted to see if there feels like a viable path forward for v1.
> 
> Although v1.22.2 is currently marked as `latest`, I'm hitting issues with `v1.22.3` continuing to get pulled into my app. I can't quite tell why -- it may be some kind of transitive dependency that is still referencing `^v1.22.3`. For what it's worth, I'm using Yarn as the package manager.
> 
> I'm curious if there's any appetite to publish out a `v1.22.4` which rolls back the change introduced in `v1.22.3`.
> 
> For additional context, I'm hitting the problem from pulling in `@opentelemetry/instrumentation` which has a transitive dependency on `resolve` by way of `require-in-the-middle`.

Maybe caused by eslint-plugin-import. There is a release with eslint-plugin-import about 5 days ago，and they bumped version of `resolve` on Apr 15 (https://github.com/import-js/eslint-plugin-import/commit/261ee3aa7666edb0131e08db3d3d3428b013df42).

As it happens，eslint-plugin-import has no release from Apr until 5 days ago，so they didn’t receive bug report of `resolve` until recent days.🤣

> see https://github.com/import-js/eslint-plugin-import/issues/2846

**Comment by schmalzs** [comment] 2023-08-02 18:32
Ah, thanks for the heads up on that, 

> > Hi all -- appreciate your thought on this issue. I see there hasn't been a lot of activity and wanted to see if there feels like a viable path forward for v1.
> > Although v1.22.2 is currently marked as `latest`, I'm hitting issues with `v1.22.3` continuing to get pulled into my app. I can't quite tell why -- it may be some kind of transitive dependency that is still referencing `^v1.22.3`. For what it's worth, I'm using Yarn as the package manager.
> > I'm curious if there's any appetite to publish out a `v1.22.4` which rolls back the change introduced in `v1.22.3`.
> > For additional context, I'm hitting the problem from pulling in `@opentelemetry/instrumentation` which has a transitive dependency on `resolve` by way of `require-in-the-middle`.
> 
> Maybe caused by eslint-plugin-import. There is a release with eslint-plugin-import about 5 days ago，and they bumped version of `resolve` on Apr 15 ([import-js/eslint-plugin-import@261ee3a](https://github.com/import-js/eslint-plugin-import/commit/261ee3aa7666edb0131e08db3d3d3428b013df42)).
> 
> As it happens，eslint-plugin-import has no release from Apr until 5 days ago，so they didn’t receive bug report of `resolve` until recent days.🤣
> 
> > see [import-js/eslint-plugin-import#2846](https://github.com/import-js/eslint-plugin-import/issues/2846)

Ah, thanks for the heads up on that 👍

In case anyone else lands here that is using Yarn... TIL you can use [selective dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to pin `v1.22.2`. There's a disclaimer that nested packages may not work properly, but I am seeing success with this so far 😄 

Also, appreciate the quick reply @ljharb! Still definitely interested in the `v1.22.4` publish when you have an opportunity. That'll allow me to avoid the awkward pinning of the version 🙏

**Comment by ljharb** [comment] 2023-08-04 23:35
v1.22.4 is published; this can now be closed.

I still don't want to do https://github.com/inspect-js/is-core-module/pull/14, but without that, I'm not sure how to keep `core.json` dynamically up to date with `is-core-module` while still supporting bundlers.

**Closed by ljharb** 2023-08-04 23:35 UTC
