### ISSUE TITLE
v1.18 fs/promises error

### ISSUE THREAD

**Issue by cruzdanilo** [browserify/resolve#231] opened 2020-10-22 20:10 UTC
v1.18 broke some eslint plugins inside vscode (node v12)

```js
const { appendFile } = require('fs/promises');
```
gives the following errors:
```
- Unable to resolve path to module 'fs/promises'. eslint(import/no-unresolved)
- "fs/promises" is not found. eslint(node/no-missing-require)
```
when running via cli using node v14 there is no error

**Comment by ljharb** [comment] 2020-10-22 20:16
`fs/promises` does not exist in node 12. It's only a core module in node 14+.

**Comment by ljharb** [comment] 2020-10-22 20:17
vscode should be using whatever node you have installed - in your case, it should be using node 14 if you're running your project in node 14.

**Comment by cruzdanilo** [comment] 2020-10-22 20:28
@ljharb this is a breaking change in a minor update

**Comment by ljharb** [comment] 2020-10-22 20:46
In what way is it a breaking change?

1. For `resolve`, it's an additive change (added in v1.16.0, btw, not v1.18.0), since it now reports `true` for an additional core module
1. For eslint plugins, new warnings are *not* semver-major, they are semver-minor, based on eslint's own semver policy.
1. In this case, it's clearly a bug fix, because in node 12, your code is broken, and these linting rules are catching your broken code.

**Comment by cruzdanilo** [comment] 2020-10-22 20:50
can't a ci build/deploy script run on a different node version from the production environment?
if this script stops on lint errors, wouldn't this error break it?

**Comment by ljharb** [comment] 2020-10-22 20:52
They can, but certainly shouldn't.

`resolve` has always used "the current version of node" to determine what constitutes a core module; this may just be the first time you've run into it because there aren't often new core modules added.

**Comment by ljharb** [comment] 2020-10-22 20:53
Put another way, any "fix" here would be to NEVER consider `fs/promises` a core module without a breaking change. In node 12, `fs/promises` has never actually been considered a core module by resolve or its dependents.

In other words, this isn't new breakage - in node 12, this code would never have passed the linter, as far as I can tell.

**Comment by cruzdanilo** [comment] 2020-10-22 20:58
yes, `fs/promises` + resolve@1.17.0 + node@12 definitely pass

**Comment by ljharb** [comment] 2020-10-22 21:08
oh hmm, you're right. That means that resolve v1.17 had a bug - `fs/promises` is only a core module in node `v10.0.0` and `v14+`. This remains a bugfix, albeit a potentially disruptive one - the bug was that prior to v1.18, `resolve` *incorrectly* reported that *every* possible core module was in fact a core module, even if it wasn't in that version of node.

This bug was introduced in e5da77e, in resolve v1.13.0, in #203, and was inadvertently fixed by me when I extracted `resolve`'s "is core" functionality into `is-core-module`, which began being used by `resolve` in v1.18.0.

Unfortunately, every bug fix is a breaking change for someone relying on the bug - in this case, resolve needs to match the behavior users were expecting _before_ v1.13.0 broke them, and that's what v1.18.0 fixes.

**Closed** 2020-10-24 02:32 UTC

**Comment by dlong500** [comment] 2021-03-01 18:53
I can't tell if my problem relates to this issue or not, but I'm using node 15.10 with the latest version of eslint and get an `Unable to resolve path to module` for an import like `import { stat, readdir } from 'fs/promises'`.  The odd thing is I'm finding almost nothing on Google on the topic (even though the promise-based import syntax is shown in the Node v15 docs).

**Comment by ljharb** [comment] 2021-03-01 20:49
@dlong500 are you getting that issue inside your editor, or on the command line? for example, vscode ships its own copy of node, so that's the version that `resolve` would be using.

**Comment by ljharb** [comment] 2021-03-01 21:07
I'm not sure if there's a way to configure vscode to run the proper node version, but it's always going to be a problem with vscode using a node version that doesn't match the one you use.

**Comment by dlong500** [comment] 2021-03-01 21:18
That seems like a fundamental flaw in how a linter works in the context of an editor.  Shouldn't linting always be based (as much as possible) on the production environment rather than the development environment?  In this case, it's not even the development environment, but a sub-environment specific to the editor runtime that has nothing at all to do with the actual code runtime environment(s).

IMO it seems like there should be an entirely different way of running a linter for an editor.  The version of Node included with vscode is really only for internal editor use (and is inextricably linked to the other "components" that make up the vscode runtime like electron, Chrome, v8, etc).  It has nothing to do with the actual Node version installed on the same workstation as the editor.

**Comment by ljharb** [comment] 2021-03-01 22:09
It's indeed a fundamental flaw in *in-editor linters*.

eslint itself is *ran* by node; it's impossible for it to specify which node version is used because at that point it has already been invoked.

**Comment by dlong500** [comment] 2021-03-02 04:16
Just to follow up:  I did figure out with the vscode eslint extension you can add an `eslint.runtime` setting to specify a node executable to use when running eslint.  This is supposed to be a path, but just setting `eslint.runtime: "node"` appears to be enough to get eslint to use the version of node installed on the system and not the internal version used by vscode (it probably works because it looks at the system path variable which includes the external node binary).  And yes, this does allow eslint to properly see `fs/promises` as a core module.

Thanks for the responses.  It helped me to narrow down the root cause of my issue.
