### ISSUE TITLE
intentionally malformed package.json fixture in tests breaks flowtype when checking node_modules

### ISSUE THREAD

**Issue by paritosh-yadav** [browserify/resolve#262] opened 2022-01-04 07:45 UTC
**Steps to regenerate:-**

- `npm install resolve`
- run `flow` command

flow output:-

`Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/resolve/test/resolver/malformed_package_json/package.json:2:1
Unexpected end of input, expected the token }`

     1│ {
     2│

@ljharb, Kindly respond. Thank you

**Comment by ljharb** [comment] 2022-01-04 15:06
Why is flow checking node_modules?

**Comment by TrySound** [comment] 2022-01-04 17:55
To collect published types. It finds package.json to check for entry point and cannot parse it. Why tests are published anyway? Do they or ci configs have any use in node_modules?

**Comment by ljharb** [comment] 2022-01-04 18:03
Tests are published in all my packages because `npm explore foo && npm install && npm test` should always work.

**Comment by ljharb** [comment] 2022-01-04 18:04
It seems like a bug should be filed on flow so that it doesn't fail when it encounters invalid JSON, especially inside node_modules.

**Comment by paritosh-yadav** [comment] 2022-01-05 08:29
Hi @ljharb ,

I have ignored the lib in flow config. Previously ignoring lib isn't working, but now it is.

**Comment by ljharb** [comment] 2022-01-05 16:53
I'd still suggest filing a bug on flow itself, so that *by default* it doesn't crash on this case.

Closing, since the only issue I know about here is caused by flow, and ignoring the file in flow config works. Happy to reopen if a different scenario is causing problems.

**Closed by ljharb** 2022-01-05 16:53 UTC

**Comment by jacksontims123** [comment] 2022-01-05 19:53
So you can ignore when problems arise in flow?

**Comment by ljharb** [comment] 2022-01-05 20:03
@jacksontims123 i closed this under the assumption that https://github.com/browserify/resolve/issues/262#issuecomment-1005478850 means you can indeed ignore that file path, and flow will avoid crashing.

**Comment by chrisbobbe** [comment] 2022-01-25 01:02
> It seems like a bug should be filed on flow so that it doesn't fail when it encounters invalid JSON, especially inside node_modules. Please link to it here when that’s filed.

https://github.com/facebook/flow/issues/2364
